- src/main/java/gitbal/backend/config/SwaggerConfig.java
- src/main/java/gitbal/backend/controller/CommonController.java
- src/main/java/gitbal/backend/controller/MyPageController.java
- src/main/java/gitbal/backend/controller/RegionRankController.java
- src/main/java/gitbal/backend/controller/SchoolRankController.java
- src/main/java/gitbal/backend/controller/UnivController.java
- src/main/java/gitbal/backend/controller/UserRankContorller.java
#10 
해당 작업진행
>
@leesj000603 해당 작업 확인해주세요!
closes #10
> [feat] swagger ui 적용한 작업 진행

- Dockerfile
- build.gradle
#16 
dockerfile multistaging 방식으로 진행
dockerfile 작성 후 dockerhub에 올려서 ec2 인스턴스에 올려놨음!
- 작업 진행시 오류 사항으로 맥북에서 실행하였을 때 `docker build -t --platform linux/amd64` 를 붙여야지 진행이 된다.
- docker 진행할 때 build를 하고 진행해야 했다.
>
> [feat] dockerfile 작성 및 ec2에 올려놓는 작업 진행 (swagger를 상시 확인하기 위해)

- src/main/java/gitbal/backend/mock/MockDataGenerator.java
Spring CommandLineRunner를 통해 생성
- 추가로 ApplicationRunner도 있는데 둘의 차이점은 run 메서드에서 넘겨받는 인자가 다른것임.
Runner는 참고로 스프링 초기 설정들이 다 끝나고 실행이 됬었음.
data.sql까지 다 실행되고 나서 실행됨 그래서 bean 같은 등록은 이미 다 되어있음.
#29 
[해당 이슈 관련 jira](https://gitbal.atlassian.net/jira/software/projects/GITBAL/boards/1?selectedIssue=GITBAL-102)
>
closes #29
> [feat] 임시 데이터 생성

- src/main/java/gitbal/backend/controller/CommonController.java
- src/main/java/gitbal/backend/entity/Region.java
- src/main/java/gitbal/backend/entity/School.java
- src/main/java/gitbal/backend/entity/dto/UserInfoDto.java
- src/main/java/gitbal/backend/entity/dto/UserInfoDto2.java
- src/main/java/gitbal/backend/entity/dto/UserScoreInfoDto.java
- src/main/java/gitbal/backend/service/UserInfoService.java
#34 
api/v1/userInfo기능 구현 및 region, school entity에 getter Annotation 추가
>
closes #34
> Feature/#34 api/v1/userInfo

- src/main/java/gitbal/backend/controller/UserRankContorller.java
- src/main/java/gitbal/backend/domain/UserRaceStatus.java
- src/main/java/gitbal/backend/entity/dto/UserRankRaceResponseDto.java
- src/main/java/gitbal/backend/entity/dto/UserRankScoreResponseDto.java
- src/main/java/gitbal/backend/exception/GlobalExceptionHandler.java
- src/main/java/gitbal/backend/exception/UserRankException.java
- src/main/java/gitbal/backend/mock/MockDataGenerator.java
- src/main/java/gitbal/backend/repository/UserRepository.java
- src/main/java/gitbal/backend/service/UserRankService.java
- src/main/java/gitbal/backend/service/UserService.java
#33 
제목에 적힌 api들 실행가능하게 수행해놓음.
>
> [feat] userRank 도메인 작업하기(/api/v1/userRank/userscore, /api/v1/userRank/race)

- src/main/java/gitbal/backend/controller/CommonController.java
- src/main/java/gitbal/backend/domain/GitbalScore.java
- src/main/java/gitbal/backend/entity/dto/UserInfoDto.java
- src/main/java/gitbal/backend/entity/dto/UserScoreInfoDto.java
- src/main/java/gitbal/backend/service/UserInfoService.java
- src/main/java/gitbal/backend/service/UserService.java
#33 
오류났던 클래스 이름 수정!
급히 진행해야하므로 바로 대면으로 회의후 머지 진행!
>
> [fix] 이름 잘못된 것들 수정! main에서 땡겨올 때 오류 발생!

- src/main/java/gitbal/backend/controller/UnivController.java
> [docs] #38 - univcontroller 태그 작업완료로 변경

- src/main/java/gitbal/backend/controller/UserRankContorller.java
- src/main/java/gitbal/backend/domain/RegionRaceStatus.java
- src/main/java/gitbal/backend/domain/SchoolRaceStatus.java
- src/main/java/gitbal/backend/entity/dto/RegionRankDto.java
- src/main/java/gitbal/backend/entity/dto/RegionRankRaceResponseDto.java
- src/main/java/gitbal/backend/entity/dto/SchoolRankRaceResponseDto.java
- src/main/java/gitbal/backend/repository/RegionRepository.java
- src/main/java/gitbal/backend/service/RegionService.java
- src/main/java/gitbal/backend/service/UserRankService.java
- src/main/java/gitbal/backend/service/UserService.java
이전 api/v1/userRank/school과 같은 작업을 수행함!
다만 어느 entity로 race한느지 바뀌었을 뿐! #40 커밋로그 참고!
추가적으로 프론트 요청에 따른 api 명세서 수정 및 응답 dto 수정
#43 
#45 
[jira 이슈참고](https://gitbal.atlassian.net/browse/GITBAL-116?atlOrigin=eyJpIjoiNTczZTkyODc2NTdjNDFjYTgxMjUzNmMzMDE1ODhkM2MiLCJwIjoiaiJ9)
>
closes #43 
closes #45
> [feat] userRank도메인 /api/v1/userRank/region 작업 진행! + [fix] api 명세서 수정에 따른 response dto 수정

- src/main/java/gitbal/backend/controller/UserRankContorller.java
- src/main/java/gitbal/backend/domain/LanguageResponseConverter.java
- src/main/java/gitbal/backend/entity/MajorLanguage.java
- src/main/java/gitbal/backend/entity/dto/MajorLanguageDto.java
- src/main/java/gitbal/backend/entity/dto/UserRankMajorLanguageResponseDto.java
- src/main/java/gitbal/backend/mock/MockDataGenerator.java
- src/main/java/gitbal/backend/service/MajorLanguageService.java
- src/main/java/gitbal/backend/service/UserRankService.java
#44 
작업 진행하였던 내용 관련하여
[Jira 참고](https://gitbal.atlassian.net/browse/GITBAL-119?atlOrigin=eyJpIjoiODFiM2Q1YWY1MzFlNDE3Mjk5MjRkZGU2ODNlM2UzOTgiLCJwIjoiaiJ9) 테스트까지 완료함.
>
closes #44
> [feat] userRank도메인 /api/v1/userRank/lang 작업 진행!

- src/main/java/gitbal/backend/controller/RegionRankController.java
- src/main/java/gitbal/backend/controller/SchoolRankController.java
- src/main/java/gitbal/backend/entity/dto/FirstRankRegionDto.java
- src/main/java/gitbal/backend/entity/dto/FirstRankSchoolDto.java
- src/main/java/gitbal/backend/repository/RegionRepository.java
- src/main/java/gitbal/backend/repository/SchoolRepository.java
- src/main/java/gitbal/backend/service/RegionRankService.java
- src/main/java/gitbal/backend/service/SchoolRankService.java
#50 
firstRankSchoolDto 파일 추가, schoolRankController 작성, schoolRepository 쿼리 추가, schoolRankService 작성 
>schoolChangeScore 부분은 미구현, null처리 
> Feature/#50 api/v1/school rank/first school

- src/main/java/gitbal/backend/controller/RegionRankController.java
- src/main/java/gitbal/backend/entity/dto/FirstRankRegionDto.java
- src/main/java/gitbal/backend/repository/RegionRepository.java
- src/main/java/gitbal/backend/service/RegionRankService.java
#51 
FirstRankRegionDto 파일 추가, RegionRankController, RegionRankService, RegionRepository 작성
>firstSchool과 마찬가지로, regionChangeScore미구현, null처리
> [feat] #51 - regionRank/firstRegion

- src/main/java/gitbal/backend/controller/MainPageController.java
- src/main/java/gitbal/backend/domain/PageCalculator.java
- src/main/java/gitbal/backend/entity/Grade.java
- src/main/java/gitbal/backend/entity/User.java
- src/main/java/gitbal/backend/entity/dto/MainPageUserDto.java
- src/main/java/gitbal/backend/entity/dto/MainPageUserResponseDto.java
- src/main/java/gitbal/backend/entity/dto/PageInfoDto.java
- src/main/java/gitbal/backend/exception/GlobalExceptionHandler.java
- src/main/java/gitbal/backend/exception/MainPageException.java
- src/main/java/gitbal/backend/mock/MockDataGenerator.java
- src/main/java/gitbal/backend/service/LoginService.java
- src/main/java/gitbal/backend/service/MainPageService.java
#52 
[jira이슈참고](https://gitbal.atlassian.net/jira/software/projects/GITBAL/boards/1?selectedIssue=GITBAL-127)
중간중간 TODO 관련한 작업들은 이후 새로운 issue들에서 반영할 예정!
- 기획 확정되지 않은 부분
코드 개발 도중 여러가지 리팩토링 요소들에 대해서 발겨하였습니다! 그리고 공통로직같은 부분이요! 그래서 이후에 진행할 때 저희 같이 보고 수정해봐야할 거 같아요!
ex) Paging 처리와 같은 부분에 대한 처리 -> PageCalculator 바탕으로 로직 구성해서 처리
closes #52
> [feat] /api/v1/mainPage/users 개발

- src/main/java/gitbal/backend/controller/MainPageController.java
- src/main/java/gitbal/backend/controller/RegionRankController.java
- src/main/java/gitbal/backend/controller/SchoolRankController.java
- src/main/java/gitbal/backend/entity/dto/FirstRankRegionDto.java
- src/main/java/gitbal/backend/entity/dto/FirstRankSchoolDto.java
- src/main/java/gitbal/backend/repository/RegionRepository.java
- src/main/java/gitbal/backend/repository/SchoolRepository.java
- src/main/java/gitbal/backend/service/RegionRankService.java
- src/main/java/gitbal/backend/service/SchoolRankService.java
> [chore] 일부 작성하지 못했던 swagger 문서 설명 작성

- src/main/java/gitbal/backend/controller/MainPageController.java
- src/main/java/gitbal/backend/domain/PageCalculator.java
- src/main/java/gitbal/backend/repository/UserRepository.java
- src/main/java/gitbal/backend/service/MainPageService.java
#54 
[jira링크 참고](https://gitbal.atlassian.net/jira/software/projects/GITBAL/boards/1?selectedIssue=GITBAL-129)
해당 작업 진행
jira 내부 자료 참고
>
closes #54
> [feat] /api/v1/mainPage/search 개발

- src/main/java/gitbal/backend/controller/MainPageController.java
- src/main/java/gitbal/backend/entity/dto/MainPageFirstRankResponseDto.java
- src/main/java/gitbal/backend/service/MainPageService.java
#53 
[jira링크 참고](https://gitbal.atlassian.net/jira/software/projects/GITBAL/boards/1?selectedIssue=GITBAL-128)
/api/v1/mainPage/firstRank 기능 구현
>
closes #53
> [feat] #53 - /api/v1/mainPage/firstRank 기능 구현

- src/main/java/gitbal/backend/controller/MainPageController.java
> [chore] #53 - swagger 관련 문서 mainPageController에 작성

- src/main/java/gitbal/backend/controller/MainPageController.java
- src/main/java/gitbal/backend/exception/GlobalExceptionHandler.java
- src/main/java/gitbal/backend/exception/MainPageException.java
- src/main/java/gitbal/backend/exception/MainPageFirstRankException.java
- src/main/java/gitbal/backend/exception/NotFoundUserException.java
- src/main/java/gitbal/backend/exception/WrongPageNumberException.java
- src/main/java/gitbal/backend/service/MainPageService.java
#60 
- 조금 더 exception 세분화
- 에러코드 500 -> 400 으로 수정
- 메시지는 CustomException message는 해당 클래ㅏ스에서 진행하도록 함.
>
closes #60
> [feat] #60 - mainPageException 처리 관련하여서 수정

- src/main/java/gitbal/backend/config/SecurityConfig.java
- src/main/java/gitbal/backend/controller/SchoolRankController.java
- src/main/java/gitbal/backend/entity/dto/MySchoolInfoResponseDto.java
- src/main/java/gitbal/backend/exception/GlobalExceptionHandler.java
- src/main/java/gitbal/backend/exception/NotLoginedException.java
- src/main/java/gitbal/backend/repository/SchoolRepository.java
- src/main/java/gitbal/backend/service/SchoolRankService.java
#65 
- 1차적으로 로컬안에서 토큰 교환 후 인증이 되는지 확인이 가능했습니다.
- 그렇지만 아직 fe 와 연결한 이후 api 통신 테스트를 통해서 추가적으로 수정해야할 사항들 지속해서 진행할 예정입니다.
- 1차 진행과 같은 경우 [jira링크](https://gitbal.atlassian.net/jira/software/projects/GITBAL/boards/1?selectedIssue=GITBAL-135)를 확인해주세요
>
MySchoolInfoResponseDto에 대한 이름을 다른걸로 어떻게 바꾸면 좋을지...? 고민이네요
closes #65
> [feat] #65 - /api/v1/schoolRank/mySchool

- src/main/java/gitbal/backend/config/SwaggerConfig.java
#70 
다음과 같이 토큰을 넣을 수 있습니다.
>
closes #70
> [chore] #70 - swagger에 jwt 토큰 넣어서 인증한 상태로 진행할 수 있게 추가

- src/main/java/gitbal/backend/controller/SchoolRankController.java
- src/main/java/gitbal/backend/exception/GlobalExceptionHandler.java
- src/main/java/gitbal/backend/exception/NotFoundSchoolException.java
- src/main/java/gitbal/backend/repository/SchoolRepository.java
- src/main/java/gitbal/backend/service/SchoolRankService.java
#54 참고하여 진행했음.
#79 
- /api/v1/schoolRank/search 구현했습니다.
- 전반적으로 #54 와 기능적으로 똑같게 구현하였습니다.
- Pagination 관련하여 10개씩 지정하여 보이도록 하였습니다.
>
이후 pagination 관련 계산하는 것은 하나로 묶어서 진행해야할 거 같아요!
closes #79
> [feat] #79 - /api/v1/schoolRank/search 구현 진행

- src/main/java/gitbal/backend/entity/RefreshToken.java
- src/main/java/gitbal/backend/repository/RefreshTokenRepository.java
- src/main/java/gitbal/backend/security/OAuth2AuthenticationSuccessHandler.java
- src/main/java/gitbal/backend/security/jwt/JwtTokenProvider.java
#74 
코드 내부 필드명 수정에 따른 다른 메서드 명 변경 작업 -> userId보다는 userNickname이 맞는 표현인 것 같음!
>
> [chore] #74 - 이름 수정 -> userId보다는 닉네임인거 같아서 변경!

- src/main/java/gitbal/backend/config/SecurityConfig.java
- src/main/java/gitbal/backend/controller/CommonController.java
- src/main/java/gitbal/backend/domain/AuthenticationChecker.java
- src/main/java/gitbal/backend/entity/dto/UserInfoDto.java
- src/main/java/gitbal/backend/exception/GlobalExceptionHandler.java
- src/main/java/gitbal/backend/exception/NotDrawUserException.java
- src/main/java/gitbal/backend/service/MyPageService.java
- src/main/java/gitbal/backend/service/UserInfoService.java
#86 
같이 진행한 내용이어서 fileChanged 확인
>
> [refactor] 0519 대면 코드 리팩토링 진행

- src/main/java/gitbal/backend/config/SecurityConfig.java
- src/main/java/gitbal/backend/security/OAuth2AuthenticationSuccessHandler.java
#88 
cors 백엔드단 처리 진행했습니다.
이전
이후
>
> [feat] #88 - cors설정 진행

- src/main/java/gitbal/backend/api/auth/controller/AuthController.java
- src/main/java/gitbal/backend/api/auth/controller/LoginController.java
- src/main/java/gitbal/backend/api/auth/service/AuthService.java
- src/main/java/gitbal/backend/api/auth/service/LoginService.java
- src/main/java/gitbal/backend/api/userPage/service/MyPageService.java
- src/main/java/gitbal/backend/global/config/SecurityConfig.java
- src/main/java/gitbal/backend/global/security/OAuth2AuthenticationSuccessHandler.java
- src/main/java/gitbal/backend/global/security/jwt/JwtTokenProvider.java
- src/main/java/gitbal/backend/global/util/AuthenticationChecker.java
#92 
이전에 token으로 시도했다가 못했던 부분에 대하여 임의의 fe 만들어서 작업진행
>
closes #92
> [fix] loginAPI 관련 이전 방식과 다르게 고치는 작업 진행

- src/main/java/gitbal/backend/api/schoolPage/service/SchoolRankService.java
- src/main/java/gitbal/backend/api/userPage/controller/MyPageController.java
- src/main/java/gitbal/backend/api/userPage/service/MyPageService.java
- src/main/java/gitbal/backend/domain/region/RegionService.java
- src/main/java/gitbal/backend/domain/school/SchoolService.java
- src/main/java/gitbal/backend/domain/user/UserService.java
#90 
수정 전  :  api 패키지의 특정 기능의 서비스계층 비즈니스 로직의 일부
비즈니스 로직의 가독성이 매우 떨어지고 여러 도메인의 repository에 직접 접근중, exception와 같은 부분도 비즈니스 로직에서 보여줄 필요가 없다
각 도메인의 서비스에서 이를 처리하고 api의 service에서 각 도메인의 서비스를 가져와서 함수로 사용하도록 수정
수정 과정
exception처리는 각 도메인의 service에서 처리
반복적인 코드는 함수화
같은 목적을 위한 작업 함수화
ResponseEntity는 컨트롤러에서 반환하도록 수정
결과 : 비즈니스 로직이 매우 깔끔해짐
>
> [refactor] #90 - MyPage 관련 코드 리팩토링

- src/main/java/gitbal/backend/api/auth/controller/AuthController.java
- src/main/java/gitbal/backend/api/auth/dto/JoinRequestDto.java
- src/main/java/gitbal/backend/api/auth/service/AuthService.java
- src/main/java/gitbal/backend/api/auth/service/LoginService.java
- src/main/java/gitbal/backend/api/auth/service/UserInfoService.java
- src/main/java/gitbal/backend/api/info/controller/InfoController.java
- src/main/java/gitbal/backend/api/info/service/InfoService.java
- src/main/java/gitbal/backend/api/info/service/RegionInfoService.java
- src/main/java/gitbal/backend/api/info/service/SchoolInfoService.java
- src/main/java/gitbal/backend/api/userPage/controller/MyPageController.java
- src/main/java/gitbal/backend/api/userPage/service/MyPageService.java
- src/main/java/gitbal/backend/domain/user/UserService.java
- src/main/java/gitbal/backend/global/config/SecurityConfig.java
- src/main/java/gitbal/backend/global/security/jwt/JwtAuthenticationFilter.java
> [fix] #102 0526 대면 회의 진행하면서 수정하거나, 기능 추가한 내용들 추가

- src/main/java/gitbal/backend/api/info/controller/InfoController.java
- src/main/java/gitbal/backend/api/info/service/InfoService.java
- src/main/java/gitbal/backend/api/info/service/RegionInfoService.java
- src/main/java/gitbal/backend/api/info/service/SchoolInfoService.java
#102 
이전에 api 응답이 되지 않았던 코드 수정하여 제대로 나오도록 진행!
>
> [hotfix] #102 - 응답 제대로 가지 않았던 코드 수정

- src/main/java/gitbal/backend/api/auth/dto/UserInfoDto.java
- src/main/java/gitbal/backend/api/mainPage/dto/MainPageUserDto.java
- src/main/java/gitbal/backend/api/mainPage/service/MainPageService.java
- src/main/java/gitbal/backend/api/schoolPage/dto/MySchoolInfoResponseDto.java
- src/main/java/gitbal/backend/api/schoolPage/dto/SchoolListDto.java
- src/main/java/gitbal/backend/api/schoolPage/service/SchoolRankService.java
- src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
#104
1. mainPage api에서 유저 순위를 담아야 할 부분 추가
2. schoolPage api에서 학교 등급을 담아야 할 부분 추가
3. mockDataGenerator에서 동점자 처리 로직 수정 
(동점자 처리 로직이 동점 처리 후 순위가 동점자 수만큼 더해져서 계산되도록 ex : 1, 2, 2, 2, 5, 6, 7) 
학교 등급 추가
유저 순위 추가
> 커밋 메세지 오기입 했습니다! MyPage가 아니라 MainPage입니다!!
> Feature/#104 apply schoolGrade, userRank to api

- src/main/java/gitbal/backend/api/auth/service/LoginService.java
#111 
위 사진처럼 isJoinService=true 와 같이 여부 알려주기로 함.
>
closes #111
> [feat] fe 요청사항으로 재로그인 시 서비스에 등록여부 queryParam을 통해 알려주기

- src/main/java/gitbal/backend/api/auth/controller/AuthController.java
- src/main/java/gitbal/backend/api/auth/dto/UserInfoDto.java
- src/main/java/gitbal/backend/api/auth/service/LoginService.java
- src/main/java/gitbal/backend/api/auth/service/UserAuthInfoService.java
- src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
- src/main/java/gitbal/backend/global/security/OAuth2AuthenticationSuccessHandler.java
- src/main/java/gitbal/backend/schedule/userupdate/onedaycommit/UserOneDayCommitUpdaterImpl.java
- src/main/java/gitbal/backend/schedule/userupdate/score/UserScoreUpdaterImpl.java
#99 
#117 
- MockData 생성을 진행하는데 jpa delete가 제대로 동작하지 않아 따로 로직을 작성하여 중복insert 방지
- FE_URL https://github.com/value 처리
- /api/v1/auth/userInfo api 관련하여 수정작업 진행 -> authentication으로 진행
- 해당 api response시 오류 발생하는 것 수정! -> @getter 추가
- scheduling 진행시 유저가 서비스에 제대로 학교, 지역을 등록하지 않아 온전한 등록 상태가 아니라면 업데이트 대상에서 제외하는 작업 진행
>
closes #117
> [fix] 배포 작업 진행중에 관련하여서 오류가 발생해서 오류 관련 처리 진행함.

- .gitignore
- Dockerfile
- database/conf/mysql.cnf
- docker-compose-local.yml
- docker-compose.yml
- src/main/java/gitbal/backend/api/auth/controller/AuthController.java
- src/main/java/gitbal/backend/api/auth/dto/UserInfoDto.java
- src/main/java/gitbal/backend/api/auth/service/LoginService.java
- src/main/java/gitbal/backend/api/auth/service/UserAuthInfoService.java
- src/main/java/gitbal/backend/api/healthcheck/HealthCheckController.java
- src/main/java/gitbal/backend/global/healthcheck/HealthCheckController.java
- src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
- src/main/java/gitbal/backend/global/security/OAuth2AuthenticationSuccessHandler.java
- src/main/java/gitbal/backend/schedule/userupdate/onedaycommit/UserOneDayCommitUpdaterImpl.java
- src/main/java/gitbal/backend/schedule/userupdate/score/UserScoreUpdaterImpl.java
- src/main/resources/application-db.yml
- src/main/resources/application-jwt.yml
- src/main/resources/application-oauth.yml
- src/main/resources/application-prod.yml
- src/main/resources/application-token.yml
- src/main/resources/application-univ.yml
- src/main/resources/application.yml
#99 
#117 
이제 배포 환경 분리를 위하여 local, prod 분리를 진행합니다!
fe 에게는 어떻게 실행해야하는지에 대해서 설명하기 위하여 이후 회의 진행시 대면으로 설정을 진행합니다.
이후 배포를 aws ec2에 올려서 진행하였습니다.
>
closes #99
> [feat] deploy를 위한 배포전 세팅 진행

- src/main/java/gitbal/backend/BackendApplication.java
> [feat] #99 - swagger 요청에 배포에 요청을 보낼 수 있도록 url 추가

- src/main/java/gitbal/backend/api/regionPage/dto/RegionListDto.java
- src/main/java/gitbal/backend/api/regionPage/service/RegionRankService.java
#125 
- 오타 수정 작업 진행 regionlRank -> regionRank
- 변경된 점수 관련 기본 값을 null 이 아닌 0으로 변경작업진행
>
추가로 이제는 실제 유젇르을 위한 변경 점수에 대한 로직들이 필요함에 따른 TODO 주석 작성하였습니다! 확인해주세요!
> [fix] fe요청 사항에 따른 regionRank 수정작업 진행

- src/main/java/gitbal/backend/api/auth/controller/LoginController.java
- src/main/java/gitbal/backend/domain/user/User.java
- src/main/java/gitbal/backend/domain/user/UserService.java
- src/main/java/gitbal/backend/global/security/OAuth2AuthenticationSuccessHandler.java
#128 
oauth2Login 진행시에 프로필 이미지를 업데이트하는 방식으로 진행하였습니다.
>
closes #128
> [feat] - user가 로그인시에 profileImg가 바뀐 경우가 있어 oauth2Login시 업데이트 진행

- src/main/java/gitbal/backend/api/auth/dto/UserInfoDto.java
#129 
- userInfo의 응답에 grade를 추가하여 전달합니다.
- imagName 오타 -> imgUrl로 수정
>
closes #129
> [feat] userInfo 응답에 추가로 grade 추가, imageName 오타 -> imgUrl 로 수정

- src/main/java/gitbal/backend/api/auth/dto/UserInfoDto.java
- src/main/java/gitbal/backend/api/auth/service/UserAuthInfoService.java
- src/main/java/gitbal/backend/api/regionPage/dto/MyRegionInfoResponseDto.java
- src/main/java/gitbal/backend/api/regionPage/service/RegionRankService.java
- src/main/java/gitbal/backend/api/schoolPage/dto/MySchoolInfoResponseDto.java
- src/main/java/gitbal/backend/api/userPage/service/UserRankService.java
- src/main/java/gitbal/backend/domain/user/UserRegionSchoolNameDto.java
- src/main/java/gitbal/backend/domain/user/UserService.java
#136 
```html
/api/v1/userRank/school
/api/v1/userRank/region
/api/v1/userRank/lang
/api/v1/auth/userInfo
/api/v1/schoolRank/mySchool
/api/v1/regionRank/myRegion
```
해당하는 친구들이 학교, 지역이 없으면 작동할 수 없었던 api였는데 -> 임시로 없는 경우 응답 반환할 수 있게 처리
>
이 부분에 대해서 FE측과 논의를 통해 어떻게 응답을 처리해야할 지 얘기를 나눠야 하지만 @leesj000603 의견도 궁금하네요!
> [feat] 학교, 지역이 등록되지 않은 경우에 대한 임시 처리작업 진행 -> 이후에 FE와 논의 후 응답 변경해야하지만 임시적으로 개발 진행

- src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
- src/main/java/gitbal/backend/schedule/userupdate/UserSetup.java
#144 
이전 작업을 검증하기 위하여 이제는 검증되었던 다른 메서드 말고 khyojun 유저 MockData에서 제외하고 진행
>
> [feat] #144 - mockData에서 khyojun 제거하고 학생 인증 테스트 진행

- src/main/java/gitbal/backend/api/univcert/service/UnivService.java
#144 
검증 과정에서 학교 인증 코드 틀려도 들어갈 수 있다는 것을 확인하고 응답으로 에러 코드 던져서 처리 
>
> [feat] #144 - 코드 틀렸을 경우 에러코드 반환하도록 설정

- .github/workflows/gradle.yml
- Dockerfile
- src/main/java/gitbal/backend/api/auth/service/AuthService.java
- src/main/java/gitbal/backend/api/univcert/service/UnivService.java
- src/main/java/gitbal/backend/domain/region/RegionService.java
- src/main/java/gitbal/backend/domain/school/SchoolService.java
- src/main/java/gitbal/backend/domain/user/User.java
- src/main/java/gitbal/backend/domain/user/UserService.java
- src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
- src/main/java/gitbal/backend/schedule/userupdate/UserSetup.java
#150 
- 회원 가입시 등수 반영을 위한 작업을 위해 바로 실행
>
> [hotfix] #150 - 회원 가입시 즉시 업데이트 진행하는 방식으로 진행

- .github/workflows/action.yml
- docker-compose.yml
- src/main/java/gitbal/backend/global/healthcheck/HealthCheckController.java
#152 
blue green 무중단 배포 전략을 위한 작업들을 진행하였습니다.
1. 인스턴스 내부의 배포 스크립트를 통하여서 전환 과정을 진행.
2. nginx 설정 파일 수정하여 진행
>
> [feat] 무중단 배포를 위한 수정 과정 진행

- .github/workflows/action.yml
- docker-compose.yml
- src/main/java/gitbal/backend/global/healthcheck/HealthCheckController.java
#152 
무중단 배포를 위한 스크립트 수정 및 nginx 파일 일부 변경하였습니다!
>
closes #152
> #152 내용 develop 에서 main으로 옮기기

- docker-compose.yml
#152 
배포 과정중 오류가 일어났던 부분을 수정하였습니다.
>
> [hotfix] #152 - 볼륨 선언 관련 수정

- docker-compose.yml
#152 
배포 스크립트와 컨테이너 이름을 맞추기 위하여 컨테이너 이름 지정
>
> [hotfix] 스크립트에 맞추기 위해 container이름 지정해서 진행하기

- src/main/java/gitbal/backend/api/userPage/controller/MyPageController.java
- src/main/java/gitbal/backend/api/userPage/controller/UserRankContorller.java
- src/main/java/gitbal/backend/api/userPage/service/UserRankService.java
- src/main/java/gitbal/backend/domain/user/UserRaceStatus.java
- src/main/java/gitbal/backend/domain/user/UserRepository.java
- src/main/java/gitbal/backend/domain/user/UserService.java
- src/main/java/gitbal/backend/global/util/SurroundingRankStatus.java
- src/test/java/gitbal/backend/domain/user/UserServiceTest.java
- 연관되어서 해당 api에게만 종속되는 부분도 동반하여 삭제작업 진행하였습니다.
#163  
이제 사용되지 않을 /api/v1/userRank/raced 작업 진행했습니다.
>
> [fix] /api/v1/userRank/raced 삭제 작업 진행 : 모각코를 통하여 작업 현황 공유 및 리뷰 완료

- src/main/java/gitbal/backend/api/regionPage/controller/RegionRankController.java
- src/main/java/gitbal/backend/api/regionPage/dto/UserInfoByRegion.java
- src/main/java/gitbal/backend/api/regionPage/dto/UserPageListByRegionResponseDto.java
- src/main/java/gitbal/backend/api/regionPage/service/RegionRankService.java
- src/main/java/gitbal/backend/api/schoolPage/controller/SchoolRankController.java
- src/main/java/gitbal/backend/api/schoolPage/dto/UserInfoBySchool.java
- src/main/java/gitbal/backend/api/schoolPage/dto/UserPageListBySchoolResponseDto.java
- src/main/java/gitbal/backend/api/schoolPage/service/SchoolRankService.java
- src/main/java/gitbal/backend/domain/user/User.java
- src/main/java/gitbal/backend/domain/user/UserRepository.java
- src/main/java/gitbal/backend/global/exception/RegionRankPageUserInfoByRegionException.java
- src/main/java/gitbal/backend/global/exception/SchoolRankPageUserInfoBySchoolException.java
- src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
#176 
지역 랭킹, 학교 랭킹 페이지에서 각 도메인에 맞게 해당 내용의 지역 이름, 학교 이름을 클릭하였을 때 해당 이름에 맞는 유저 리스트를 점수에 따라 순위대로 보여주는 작업 진행했습니다.
**url : /api/v1/~~Rank/userList?page=~~&~~Name=~~**
>
이전에 승준씨가 작성해주신 코드를 참고하며 진행을 하였습니다! 혹시나 궁금하신 사항이 있으시면 말씀해주세요! 
closes #176
> [feat] 학교, 지역 클릭시 해당하는 도메인에 맞게 학생들을 랭킹 순서대로 보여주는 기능

- docker-compose-local.yml
- docker-compose.yml
- src/main/java/gitbal/backend/BackendApplication.java
- src/main/java/gitbal/backend/global/config/SwaggerConfig.java
- src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
- src/main/resources/application-db.yml
#180 
- User가 3000개가 들어가고 UserName 겹치는 경우 식별자 사용해 해결하기
- swagger의 요청 보내는 칸에 있는 api.gitbal.xyz -> api.rankit.run 으로 변경하여 요청 서버로 날릴 수 있도록 하기
- rankit 프로젝트 변경에 따른 네이밍들 수정 및 github 계정 옮김에 따른 작업 진행
-  url 변경에 따른.env 수정작업들 진행
-  설명 관련 gitbal -> rankit에 맞게 수정하는 작업 진행
**추가로 노션의 회의록 아래 작업내용 참고해서 진행해야 할 로컬 환경변수 작업 진행해주셔야합니다!**
>
- closes #180
> [fix] https, 바뀐 도메인 적용 과정에서 발생했던 문제 및 바뀐 프로젝트명에 따른 파일들 수정에 다른 코드 변경사항 적용

- src/main/java/gitbal/backend/api/badge/controller/BadgeController.java
- src/main/java/gitbal/backend/api/badge/dto/BadgeResponseDTO.java
- src/main/java/gitbal/backend/api/badge/service/BadgeService.java
- src/main/java/gitbal/backend/api/badge/service/BadgeServiceImpl.java
#182
hithub꾸미기용 badge를 만들기 위한 user정보
- 성공
- 실패
>
> [feat] #182 - Badge api 구현

- src/main/java/gitbal/backend/api/badge/controller/BadgeController.java
- src/main/java/gitbal/backend/api/badge/service/BadgeServiceImpl.java
- src/main/java/gitbal/backend/global/exception/BadgeException.java
- src/main/java/gitbal/backend/global/handler/GlobalExceptionHandler.java
#182
- 성공적으로 user 정보를 찾아 전송하는 경우 - 200
- user가 존재하지 않는 경우 - 400
- 그 외 오류 - 500
으로 http status
status가 넘어오지 않던 기존 문제 해결
>
> [feat] #182 - http status 담기 위한 수정

- src/main/java/gitbal/backend/api/auth/controller/AuthController.java
- src/main/java/gitbal/backend/api/auth/dto/GitbalApiDto.java
- src/main/java/gitbal/backend/api/auth/service/AuthService.java
- src/main/java/gitbal/backend/api/auth/service/LoginService.java
- src/main/java/gitbal/backend/api/mainPage/controller/MainPageController.java
- src/main/java/gitbal/backend/api/mainPage/dto/MainPageUserDto.java
- src/main/java/gitbal/backend/api/mainPage/service/MainPageService.java
- src/main/java/gitbal/backend/api/schoolPage/service/SchoolRankService.java
- src/main/java/gitbal/backend/api/userPage/controller/UserRankContorller.java
- src/main/java/gitbal/backend/api/userPage/dto/UserRankExpResponseDto.java
- src/main/java/gitbal/backend/api/userPage/service/UserRankService.java
- src/main/java/gitbal/backend/domain/user/UserRepository.java
- src/main/java/gitbal/backend/domain/user/UserService.java
- src/main/java/gitbal/backend/global/constant/Grade.java
- src/main/java/gitbal/backend/global/exception/UnivCertStartException.java
- src/main/java/gitbal/backend/global/exception/UserHasNoMajorLanguageException.java
- src/main/java/gitbal/backend/global/exception/UserHasNoRegionException.java
- src/main/java/gitbal/backend/global/exception/UserHasNoSchoolException.java
- src/main/java/gitbal/backend/global/exception/UserRankingException.java
- src/main/java/gitbal/backend/global/handler/GlobalExceptionHandler.java
- src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
- src/main/java/gitbal/backend/global/security/jwt/JwtAuthenticationFilter.java
- src/main/java/gitbal/backend/global/security/jwt/JwtTokenProvider.java
#190 #192 #193 #195
- #190 
- #192 
- #193 
- #195 
작업 내용 관련하여 노션 qa노트 안을 참고해주세요!
>
작업내용이 조금 많습니다! 차근히 봐주시면 좋을 거 같습니다!
closes #190 #192 #193 #195
> [feat] api part 1 검토 작업 진행

- src/main/java/gitbal/backend/domain/user/UserService.java
- src/main/java/gitbal/backend/global/constant/Grade.java
- src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
#190 #195 
- 머지한 이후 급히 발견되었던 오류 처리하였습니다! PURPLE 등급이었을 때 상한값을 120000점으로 잡아놔서 그 이상의 점수였을 때는 연산 시 오류가 발생하였던 오류였는데요! 현재 다시 수정하여 기능 되는 부분 확인하였습니다!
- 추가로 테스트 코드 관련하여 120000점 까지 하여 여러 GRADE 에서 확인하도록 수정 진행하였습니다.
- PURPLE의 경우 상한값이 없기에 LONG의 MAX_VALUE로 잡았습니다!
>
Closes #190 #195
> [fix] #190 - 경험치 계산 과정중 PURPLE 등급일때 났던 오류 해결

- src/main/java/gitbal/backend/api/auth/dto/UserInfoDto.java
- src/main/java/gitbal/backend/api/mainPage/dto/MainPageUserDto.java
- src/main/java/gitbal/backend/api/mainPage/service/MainPageService.java
- src/main/java/gitbal/backend/api/regionPage/dto/RegionListDto.java
- src/main/java/gitbal/backend/api/regionPage/dto/UserInfoByRegion.java
- src/main/java/gitbal/backend/api/regionPage/service/RegionRankService.java
- src/main/java/gitbal/backend/api/schoolPage/dto/UserInfoBySchool.java
- src/main/java/gitbal/backend/api/schoolPage/service/SchoolRankService.java
- src/main/java/gitbal/backend/api/userPage/dto/FriendSuggestDto.java
#209 
nickname → username
score → userscore
(프로필이미지) imgUrl → profileImg
rank → userRank
fe에서 요청한 변수명 수정 관련 대응
>
이후 다른 문제들에 대해서는 작업량이 클 거 같아 #210  #211 에서 진행하도록 하겠씀다!
> [fix] #209 - apiIssue관련 정리 네이밍 관련 정리

- src/main/java/gitbal/backend/api/userPage/dto/IntroductionResponseDto.java
- src/main/java/gitbal/backend/api/userPage/dto/IntroductionupdateRequestDto.java
- src/main/java/gitbal/backend/api/userPage/service/MyPageService.java
- src/main/java/gitbal/backend/domain/introduction/Introduction.java
- src/main/java/gitbal/backend/domain/introduction/infra/IntroductionRepositoryImpl.java
#210 
introduction에서 title이 없었기 때문에 entity에 추가 후 
자기소개 조회, 수정 api및 dto에 이를 반영
>
> [feat] #210 - 자기소개에 제목 추가

- src/main/java/gitbal/backend/global/mock/MockDataGenerator.java
> ex) #222 
mock data의 img url 수정
> [feat] #222 - mock data의 img url 수정

- src/main/java/gitbal/backend/api/userPage/controller/UserPageController.java
- src/main/java/gitbal/backend/api/userPage/dto/ModifySchoolRequestDto.java
- src/main/java/gitbal/backend/api/userPage/service/UserPageService.java
- src/main/java/gitbal/backend/domain/region/Region.java
- src/main/java/gitbal/backend/domain/region/application/RegionService.java
- src/main/java/gitbal/backend/domain/school/School.java
- src/main/java/gitbal/backend/domain/school/SchoolService.java
- src/main/java/gitbal/backend/domain/user/UserService.java
- src/main/java/gitbal/backend/schedule/userupdate/score/UserScoreUpdaterImpl.java
#229 
긴급사항이라 바로 올리겠습니다! 테스트 완료하였습니다!
>
> [hotfix] #229 - 학교, 지역 수정시 점수 반영되고 랭킹 업데이트 구현, 학교 수정시 인증 진행하도록 구현

- src/main/java/gitbal/backend/domain/region/application/RegionService.java
- src/main/java/gitbal/backend/domain/school/SchoolService.java
- src/main/java/gitbal/backend/domain/user/UserService.java
> [hotfix] #229 -  지역변경 수정

- src/main/java/gitbal/backend/api/guestBookPage/controller/GuestBookPageController.java
- src/main/java/gitbal/backend/api/guestBookPage/dto/GuestBookWriteRequestDto.java
- src/main/java/gitbal/backend/api/regionPage/service/RegionRankService.java
#232 
#232 이슈 대응하였습니다.
- 지역 페이지네이션 관련 -> 지역별 유저 조회시 10개씩 조회되는 것이 있어 변경하였습니다!
- 게시판 조회 "" 백슬래시 이슈 -> dto 를 통해 해결하였습니다.
>
> [hotfix] #232 - fe 이슈 대응 - 지역 페이지네이션 및 게시판 조회 이슈 검토

- src/main/java/gitbal/backend/api/userPage/dto/UserRankExpResponseDto.java
- src/main/java/gitbal/backend/api/userPage/service/UserRankService.java
#232 
추가적으로 fe 에서 요구한 사항들 대응 - 응답 양식 변경
>
> [hotfix] - userRank 보여주는 response dto 변경 (fe 요구사항)

- src/main/java/gitbal/backend/api/userPage/service/UserPageService.java
#242 
school, region이 null 이된 친구를 추천하는 case를 처리하였습니다.
>
> [hotfix] suggested 된 친구 school, region 비어있는 경우 처리
